from django.core.exceptions import ValidationError


class ZipCodeValidationError(ValidationError):
    pass
